### ISSUE TITLE
RNN part1

### ISSUE THREAD

**Issue by rogertrullo** [peterroelants/peterroelants.github.io#10]
Hi, I think there is a mistake in the equation ds_k/ds_{k-m}... in the last factor you have ds_{k-m+1}/ds_{k-1} but I think it should be ds_{k-m+1}/ds_{k-m}

**Comment by peterroelants** [comment]
Hey, You are correct, there was indeed a mistake, thanks for bringing it up. I pushed a change to fix it.

Best regards,
Peter
