### ISSUE TITLE
missing - in negative log marginal likelihood 

### ISSUE THREAD

**Issue by flydream0428** [peterroelants/peterroelants.github.io#14]
in gaussian-process-kernel-fitting.ipynb, do we need a '-' for the negative log marginal likelihood? 
https://peterroelants.github.io/posts/gaussian-process-kernel-fitting/

**Comment by WT215** [comment]
> in gaussian-process-kernel-fitting.ipynb, do we need a '-' for the negative log marginal likelihood?
> https://peterroelants.github.io/posts/gaussian-process-kernel-fitting/

I have a similar feeling, seems missing "-".

**Comment by peterroelants** [comment]
Thanks for spotting, added the negative sign to the formula.
