### ISSUE TITLE
Link to the IPYNB notebook mentioned in https://peterroelants.github.io/posts/rnn-implementation-part02/ is broken

### ISSUE THREAD

**Issue by tarmas99** [peterroelants/peterroelants.github.io#37]
In the blog https://peterroelants.github.io/posts/rnn-implementation-part02/ , at the end there is a link to the IPYNB which redirects to

https://github.com/peterroelants/peterroelants.github.io/blob/main/notebooks/RNN_implementation/rnn-implementation-part02.ipynb

but it is actually

https://github.com/peterroelants/peterroelants.github.io/blob/main/notebooks/rnn_implementation/rnn-implementation-part02.ipynb

Need to change that in HTML file

**Comment by peterroelants** [comment]
fixed
