### ISSUE TITLE
Neural Network Intercept Bias

### ISSUE THREAD

**Issue by janisz** [peterroelants/peterroelants.github.io#9]
I am going through a NN tutorial from [this website](http://peterroelants.github.io/posts/neural_network_implementation_part03/)

I am confused about one particular paragraph in this page (screenshot below).

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ubT2X.png

1. Is the choice of the intercept bias of -1 purely arbitrary? I don't quite understand his explanation.

2. It said in the screenshot that the RBF function maps all values to a range of [0, +infinity]. However, the RBF function only maps to a range of [0,1]. Is this a mistake? And how does this positive range lead to a choice of -1 intercept bias?

From: http://stackoverflow.com/q/41989488/1387612

**Comment by peterroelants** [comment]
Thanks for the comment.
See my answer at http://stackoverflow.com/a/42436987/919431
